"""
Auto-generate README.md content for the user's photo repository.

The README is always machine-generated — never manually edited.
It is regenerated on every batch commit and included in the same commit.
"""

from __future__ import annotations

from datetime import datetime, timezone


def generate_readme(
    owner: str,
    repo_name: str,
    total_photos: int,
    total_size_bytes: int,
    last_upload: str | None,
    created_at: str | None = None,
) -> str:
    """
    Build the full README.md string for a PhotoVault photo repository.
    """
    size_str = _format_bytes(total_size_bytes)
    last_upload_str = (
        _format_dt(last_upload) if last_upload else "No uploads yet"
    )
    created_str = _format_dt(created_at) if created_at else "Unknown"
    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    return f"""# 📷 {repo_name}

> Managed by **[PhotoVault](https://github.com/photovault)** — self-hosted photo
> storage backed by GitHub. Do not edit this file manually; it is regenerated
> on every upload.

---

## 📊 Stats

| Key | Value |
|-----|-------|
| Total photos | {total_photos:,} |
| Total size | {size_str} |
| Last upload | {last_upload_str} |
| Repository created | {created_str} |
| README updated | {now_str} |

## 🗂 Repository structure

```
{repo_name}/
├── originals/          — Full-resolution original files
│   └── YYYY/MM/        — Organised by capture year and month
├── thumbs/             — 400px-wide JPEG thumbnails
│   └── YYYY/MM/
├── meta/               — Per-photo EXIF + GPS JSON metadata
│   └── YYYY/MM/
├── manifest.json       — Index of every photo (append-only)
└── .photovault.yml     — Repository configuration
```

## 🔒 Privacy

This repository is managed by **{owner}**. All photos are stored under their
GitHub account. PhotoVault never reads or writes to any repository it hasn't
been explicitly connected to.

---

*Last generated: {now_str}*
"""


def _format_bytes(n: int) -> str:
    if n < 1024:
        return f"{n} B"
    if n < 1024 ** 2:
        return f"{n / 1024:.1f} KB"
    if n < 1024 ** 3:
        return f"{n / 1024**2:.1f} MB"
    return f"{n / 1024**3:.2f} GB"


def _format_dt(iso: str | None) -> str:
    if not iso:
        return "Unknown"
    try:
        dt = datetime.fromisoformat(iso.replace("Z", "+00:00"))
        return dt.strftime("%Y-%m-%d %H:%M UTC")
    except Exception:
        return iso
